feat: add Codec::get_frame_info() and export Codec::NoFrame
rust-skia/rust-skia pull request #791
Opened 2023-03-28 14:50 UTC by Eywek

Hello, 

I've started to add missing methods from `SkCodec` to be able to use it for decoding GIF formats. 

I've exported `SkCodec_kNoFrame` and updated `Options.prior_frame` to be able to use it when using `get_image` on a GIF. 

I've also tried to export `get_frame_info` method (skia reference [here](https://skia.googlesource.com/skia/+/refs/heads/chrome/m112/src/codec/SkCodec.cpp#793)) but generated bindings export the wrong return type:

```rust
extern "C" {
    #[link_name = "\u{1}__ZN7SkCodec12getFrameInfoEv"]
    pub fn SkCodec_getFrameInfo(this: *mut SkCodec) -> u8;
}
```

I haven't really used `binding` so if you know how to resolve this, I'm listening

Thank you

2023-03-28 15:31 UTC, Eywek commented
> Usually a wrapper prefixed with `C_` is used to interface with Skia, see [`master`/skia-bindings/src/bindings.cpp#L105-L171](https://github.com/rust-skia/rust-skia/blob/master/skia-bindings/src/bindings.cpp?rgh-link-date=2023-03-28T15%3A01%3A25Z#L105-L171) for the already existing SkCodec wrapper C functions.

Right, thank you!

So I've added the `C_` interface with the right return type (do I need to create a another struct for FrameInfo or is it okay to expose the Sk one?)

I'm stuck now with the following code:
```rust
let infos = SkCodec_FrameInfo {};
unsafe { sb::C_SkCodec_getFrameInfo(self.native_mut(), index, &mut infos) };
```

because I need to init a `SkCodec_FrameInfo` and pass it as ref to the C++ method for populating; but obviously the Rust compiler wants me to initialize each member of `SkCodec_FrameInfo`, is here any way to avoid bothering with defaults here?

Thank you

2023-03-28 19:19 UTC, pragmatrix commented
> do I need to create a another struct for FrameInfo or is it okay to expose the Sk one

For FrameInfo it looks that it can be represented as a simple copyable type, which I prefer to mirror on the Rust side to be able to control visibility and member naming (there are exceptions where you could use the bindgen generated ones, but these require field name rewriting in the binding generator). These types are then `NativeTransmutable`, for example  the SkMatrix wrapper: https://github.com/rust-skia/rust-skia/blob/53d08abc6b664bf9a83c8f8fd4c81d2131d93360/skia-safe/src/core/matrix.rs#L33-L40. `

>because I need to init a SkCodec_FrameInfo and pass it as ref to the C++ method for populating; but obviously the Rust compiler wants me to initialize each member of SkCodec_FrameInfo, is here any way to avoid bothering with defaults here?

There is a way by using the `construct` function in Rust and on the C++ side a placement new. For Copy, aka C++ struct types, it's probably safe to leave them uninitialized, but I usually use a default and pass the mutable pointer to it with `.native_mut()`.

Here is an example with placement new (every native transmutable type implements `construct`):

Rust:

https://github.com/rust-skia/rust-skia/blob/53d08abc6b664bf9a83c8f8fd4c81d2131d93360/skia-safe/src/core/m44.rs#L729-L732

C++ 

https://github.com/rust-skia/rust-skia/blob/53d08abc6b664bf9a83c8f8fd4c81d2131d93360/skia-bindings/src/bindings.cpp#L931-L933

And here one with a default:

https://github.com/rust-skia/rust-skia/blob/53d08abc6b664bf9a83c8f8fd4c81d2131d93360/skia-safe/src/codec/_codec.rs#L67-L71

2023-03-29 09:20 UTC, pragmatrix commented on skia-safe/src/codec/_codec.rs
> +    pub alpha_type: SkAlphaType,
Use the Rust wrapper defined here: https://github.com/rust-skia/rust-skia/blob/master/skia-safe/src/core/alpha_type.rs

2023-03-29 09:31 UTC, Eywek commented
I guess I need to implement a `native_frameinfo` method to convert `SkCodec::FrameInfo` to `FrameInfo`?

2023-03-29 09:33 UTC, pragmatrix requested changes

2023-03-29 09:33 UTC, pragmatrix commented on skia-safe/src/codec/_codec.rs
> +        unsafe { sb::C_SkCodec_getFrameInfo(self.native_mut(), index, infos.native_mut()) };
The `SkCodec::getFrameInfo()` function returns a bool indicating if a frame is returned, I suggest to use it and return `Option<FrameInfo>` here.

Index should be `usize`.

2023-03-29 20:11 UTC, pragmatrix commented
I took the liberty to add the remaining types and fields needed for `FrameInfo`, which should make the layout testcases pass, and also changed the type `prior_frame` to `Option<usize>`, `None` meaning `NoFrame`.

2023-03-30 08:10 UTC, Eywek commented
> I took the liberty to add the remaining types and fields needed for `FrameInfo`, which should make the layout testcases pass, and also changed the type `prior_frame` to `Option<usize>`, `None` meaning `NoFrame`.

Great! Thank you, lgtm

2023-03-30 08:12 UTC, merged

2023-04-24 14:24 UTC, Eywek commented
Hello,

Do you know when you'll be able to release this? 

Thank you

2023-04-24 16:07 UTC, pragmatrix commented
Thank you for the ping, binaries are on its way, after that I'll release the Milestone 113 update as soon as possible.